### ISSUE TITLE
[Suggestion] Chunk Pre-generation/Data Pre-generation/Data loading

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [theorbtwo/RoughlyEnoughResources#16]
## Suggestions:

- [Chunk Pre-generation/Data Simulating](#Chunk-Pre-generation/Data-Simulating)
- [Preset Data](#Preset-Data)
- [Data loading](#Data-loading)

## Chunk Pre-generation/Data Simulating

Perhaps a way to pre-generate chunks to add data to RER would be a good idea? If possible, perhaps even simulating data would be a good idea as well because it doesn't take up any additional space from pre-generating chunks?

## Preset Data

Including Preset data with the mod would be very beneficial to users who are playing on servers. it seems that the mod is unable to generate data within servers due to the fact that the client itself is only loading said chunks.

## Data loading

Also, if this is a successor to the Just Enough Resources mod (along with NER) I would assume that you are trying to replicate as many features from those predecessors as well? If this is the case, maybe adding a feature along the lines of this should be a good idea:

> By adding world-gen.json to the JER config folder and toggling the DIY setting ingame you can make your own ore distributions

Source: [Just Enough Resources's Curseforge](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)

**Comment by theorbtwo** [comment]
Hm.  I see the dynamic nature of the data in this mod as a major improvement over Just and Not Enough Resources.  As to pregeneration, I agree that it might be useful, but is out of scope for this mod.  There are tons of ways of pregenerating chunks, and essentially any of them will work alongside of RER.

**Comment by theorbtwo** [comment]
Working as designed.  JER supporting this is a mis-feature -- modpack authors rarely actually provided this data, and when they did, it quickly became outdated.  See https://github.com/theorbtwo/RoughlyEnoughResources/issues/11
