### ISSUE TITLE
Customisation options for Vanilla and Modded resources

### ISSUE THREAD

**Issue by ghost** [theorbtwo/RoughlyEnoughResources#19]
Unless I have missed it there doesn't seem to be any way to customise anything about the 'recipes' used in this mod to show things like mob drops or ore distributions?

* I feel like the option to 'sample' the world like with the JEI implementation of this mod would be very helpful so modded resources or modded dimensions can show up accurately.

* Also the ability to hide certain recipes could also be useful, for example: telling me I can break a shulker box to get a shulker box is kinda unnecessary so I would like to be able to hide that.

   * This could also be expanded to allow for manual editing of the presented drop tables for entities if for some reason this mod doesn't detect them correctly.

Apologies if this is already possible with this mod. I dug around both here and on the CurseForge page and couldn't find any options to do so.

**Comment by theorbtwo** [comment]
Unlike the JEI version, this mod should correctly reflect the wold it is run on without needing any sort of explicit sampling or customization.  See issue #11 for more info.  Hiding "well, duh" recipes is a different bug, #21.  If you've any specific cases where an incorrect recipe is shown, or a modded dimension doesn't show up accurately, please file a different bug for it.
