### ISSUE TITLE
1.18.x Ore Distribution chart

### ISSUE THREAD

**Issue by Maja-dev** [theorbtwo/RoughlyEnoughResources#46]
The Ore Distribution/Generation chart seems to be from 1.17. 
This applies to all ores. Some ores and dirt go to ~-6 on these charts.
![image_2021-12-21_031346](https://user-images.githubusercontent.com/59345970/146859244-80804ee7-2eb9-44e3-b535-b9bf99702689.png)
Doesn't match up with current world gen as related in the example picture below. 
![b3bak5eige381](https://user-images.githubusercontent.com/59345970/146859428-af2e9ea5-fb78-482f-b783-87a972d933c4.png)

**Comment by KaneHart** [comment]
Hi there... I hope you know the difference between Iron Ore and Deepslate Iron ore :)

**Comment by ThexXTURBOXx** [comment]
The ore distribution you see is definetly from 1.18.
It is calculated with each new generated chunk dynamically.
So, if your client generates a new block, it increases its stat in the chart.

You only look at normal iron ore btw. You have to include the Deepslate version as well and you will pretty much see the expected distribution
