### ISSUE TITLE
Overworld Generation tab not showing up on server

### ISSUE THREAD

**Issue by ragsmaroon** [theorbtwo/RoughlyEnoughResources#49]
rer-2.3.0.jar
RoughlyEnoughItems-7.1.357.jar
fabric-api-0.45.1+1.18.jar

I have all mods installed client and serverside but the Overworld Generation tab won't show up, even when I go through all the tabs. Looks similar to #30 except I'm on the latest fabric api. I can provide more details if needed.

Do I need to ask the server to send information to the client or something?

**Comment by Devouring-One** [comment]
I can confirm, having the same issue. All other tabs seem to be working fine (block loot, mob loot etc)

**Comment by ragsmaroon** [comment]
For some reason it just randomly fixed itself. I didn't do anything different, I had already relaunched minecraft a bunch of times, I don't think I changed anything at all but now it just works. Sorry I can't provide help to anyone.

**Comment by Devouring-One** [comment]
Still does not work for me.

**Comment by paulhlschr** [comment]
I would like to reopen this issue, as the tab does not show up for me aswell, at least on a server environment.

**Comment by theorbtwo** [comment]
So, there's several things that could be causing this.  The first few are documentation bugs, which is to say they are things which aren't neccessarily obvious, which we should potentially make more obvious. These are:
1: The mod won't be terribly useful on the client unless it is also present on the server.
2: The various "generation" tabs mostly won't work until something has been generated there after the mod has been installed on the server.  That means that if you add the mod to an already existing world, nothing will show up until you move off the edge of the existing map and generate new chunks.
It's also completely possible that what you are seeing is a bug in the code -- the tab is actually supposed to show up in the circumstances you have, but it's not for some reason.

@Devouring-One, @paulhlschr, can you confirm that you knew the first two things and that they don't apply?
