### ISSUE TITLE
large loot tables overflow "sendlootToPlayer" packet

### ISSUE THREAD

**Issue by lorilith** [theorbtwo/RoughlyEnoughResources#5]
Latest RER and REI at the time of posting

crashes when using All Mob Heads datapack (4.0-4.3 tested, all fail) https://www.curseforge.com/minecraft/customization/all-mob-heads

https://pastebin.com/5uY2ScLj

**Comment by lorilith** [comment]
looks to be specifically the villager/zombie villager loot tables added. These are 92kb in size in order to drop job classed heads specific to the villager's job. 
removing these 92kb files (zombie and regular villager loot tables) causes the error to disappear.

**Comment by shedaniel** [comment]
It is fixed in the latest version.
