### ISSUE TITLE
Client crashes when trying to display a certain mob

### ISSUE THREAD

**Issue by ghost** [theorbtwo/RoughlyEnoughResources#7]
**Describe the bug**
When viewing mob drops through Roughly Enough Resources, the client crashes when viewing the last pane of the specific search.

**Steps to Reproduce**
- Search for 'Cursed Droplets' (Kibe mod)
- Cycle through the panes of the result
- The client crashes when switching to page 24

**Screenshots**
![image](https://user-images.githubusercontent.com/918422/87527402-5f036300-c68c-11ea-891c-38f00ccff015.png)

![image](https://user-images.githubusercontent.com/918422/87527249-22376c00-c68c-11ea-9615-4a976babb1fb.png)

**Environment (please complete the following information with the version):**
 - Minecraft 1.16.1
 - Fabric: 0.8.9+build 203
 - Roughly Enough Items 4.9.0
 - Roughly Enough Resources 2.0.2

**Logs**
https://pastebin.com/Hj1cUkcS

**Additional context**
I suspect the cause is a modded creature on page 24, I don't know which creature this could be.  If there is a way to to list all mobs for my specific combination of mods, I could find out through process of elimination.  I think it's a Better Nether mob, but can't be sure.

**Comment by dandin87** [comment]
I am experiencing the same crash with AoF3 1.4.2, looking at Kibe Cursed Droplets, there are 15 pages in this case, 1-14 work fine, I'm guessing there might be nothing on the last page as it is a null pointer exception. But that's just me guessing.

https://paste.ee/p/yiaqn

**Comment by theorbtwo** [comment]
Please check if you still have these issues, @katorone, @dandin87?  A recent change in RER attempts to work around what is if not the same problem then a related one.  (It's arguable if the problem is RER's fault or the other mod making unfounded assumptions, but if it's easy for RER to work around it, then we should.)

**Comment by ghost** [comment]
Will do.  I'll need a little time to recreate the .1 pack with as many of the mods for .3 as possible, of when this issue happened.

**Comment by ghost** [comment]
I can't reproduce this crash any more on .3.  I wasn't able to re-create the exact modpack, so I can't be 100% certain that the issue is solved.
Thanks for looking in to it!
